In [9]:
import math



R = 100
etha = 3

Smax = int(math.log(R, 3))
B = (Smax+1)*R


print('R: ', R)
print('etha: ', etha)
print('Smax: ', Smax)
print('B: ', B)


total_trial = 0
total_epoch = 0

# max_epochs = 82
# factor=3
# hyper_i = round(max_epochs * (math.log(max_epochs, factor) ** 2))
# print("max_epochs:", max_epochs)
# print("hyper_i: ", hyper_i)
#print("\n")

for s in reversed(range(Smax+1)):
    
    n = round((B/R)*(pow(etha,s)/(s+1)))
    r = round(R*pow(etha,-1*s))
    print(f"s={s}, n={n}, r={r}")

    total_trial += n

    for i in range(s+1): # hyperband_iterations
        ni = round(n*pow(etha,-1*i))
        ri = round(r*pow(etha,i))

        #if ri >= max_epochs: continue
        print(f"  i={i}, ni={ni}, epochi={ri}")

    total_epoch += n*ri
        

#print("\n")
print("total_trial: ",total_trial)
print("total_epoch: ",total_epoch)

R:  100
etha:  3
Smax:  4
B:  500
s=4, n=81, r=1
  i=0, ni=81, epochi=1
  i=1, ni=27, epochi=3
  i=2, ni=9, epochi=9
  i=3, ni=3, epochi=27
  i=4, ni=1, epochi=81
s=3, n=34, r=4
  i=0, ni=34, epochi=4
  i=1, ni=11, epochi=12
  i=2, ni=4, epochi=36
  i=3, ni=1, epochi=108
s=2, n=15, r=11
  i=0, ni=15, epochi=11
  i=1, ni=5, epochi=33
  i=2, ni=2, epochi=99
s=1, n=8, r=33
  i=0, ni=8, epochi=33
  i=1, ni=3, epochi=99
s=0, n=5, r=100
  i=0, ni=5, epochi=100
total_trial:  143
total_epoch:  13010

In [36]:
from random import random
from math import log, ceil
import heapq
import pandas as pd


def hyperband1(R, eta):
    s_max = int(log(R) / log(eta))
    B = (s_max + 1) * R

    rows = []
    for s in reversed(range(s_max + 1)):
        # initial number of configurations
        n = int(ceil(B / R / (s + 1) * eta ** s))
        # initial number of iterations per config
        r = R * eta ** (-s)

        # get hyperparameter configurations,
        # we use a random value to represent a sampled configuration
        # from a defined hyperparameter search space
        T = [random() for _ in range(n)]
        for i in range(s + 1):
            n_configs = n * eta ** (-i)
            n_iterations = r * eta ** (i)
    
            # run then return validation loss, here
            # we use a random value to represent the algorithm's
            # perform after taking in n_iterations and config as inputs
            losses = [(random(), t) for t in T]

            # return top k configurations, if we are minimizing the loss
            # then we pick the top k smallest
            top_k_losses = heapq.nsmallest(int(n_configs / eta), losses)
            T = [t for loss, t in top_k_losses]

            row = [s, n_configs, n_iterations]
            rows.append(row)

    return pd.DataFrame(rows, columns=['s', 'n_configs', 'n_iterations'])

hyperband1(R=100, eta=3)

    s  n_configs  n_iterations
0   4  81.000000      1.234568
1   4  27.000000      3.703704
2   4   9.000000     11.111111
3   4   3.000000     33.333333
4   4   1.000000    100.000000
5   3  34.000000      3.703704
6   3  11.333333     11.111111
7   3   3.777778     33.333333
8   3   1.259259    100.000000
9   2  15.000000     11.111111
10  2   5.000000     33.333333
11  2   1.666667    100.000000
12  1   8.000000     33.333333
13  1   2.666667    100.000000
14  0   5.000000    100.000000